[package]
description = "Hardware wallet support."
homepage = "http://parity.io"
license = "GPL-3.0"
name = "hardware-wallet"
version = "1.6.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.3"
parking_lot = "0.3"
hidapi = "0.3"
ethkey = { path = "../ethkey" }
ethcore-bigint = { path = "../util/bigint" }

[dev-dependencies]
rustc-serialize = "0.3"
